# Generated by Django 5.2.5 on 2025-08-24 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('conmpletada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=11),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('objetivo_diario', models.CharField(default='Enfocarse 4 hoas al día', max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tareas_completadas', models.IntegerField(default=0)),
                ('tiempo_enfoque', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
